blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/yteruel31/react-material-symbol-icons/discussions/categories/q-a
    about: Ask questions in GitHub Discussions
